// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpmgctkizfvcxdaqptfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwbWdjdGtpemZ2Y3hkYXFwdGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjkyNjksImV4cCI6MjA1Njk0NTI2OX0.PpccZ6jAwBAEjc2osaZEbJEc8tDcsImZNP71SNIQABM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);